### ISSUE TITLE
Keep old schemas available?

### ISSUE THREAD

**Issue by hotchkj** [EDSM-NET/EDDN#55]
Recent changes have removed the older schemas from the master branch. They're also not hosted on http://schemas.elite-markets.net/eddn. This makes finding an authoritative copy of the older schemas much harder than it should be for when tools transmit data using the older schemas. It would be preferable if the older schemas remained available. I understand the desire to push producers to new schemas, but consumers still have to deal with older data. At present, I have to look back through the commit history and hope I find the schemas as were published. Assistance appreciated.

**Comment by Marginal** [comment]
The network no longer allows messages sent in these old schemas, so they're not useful.
Or do you have some other need for them?

**Comment by hotchkj** [comment]
I host an archive of the messages. The older messages refer to the older schemas. I can also start archiving the schemas but that wasn't really anticipated.

**Comment by Marginal** [comment]
I take your point. I'm not sure why we started deleting obsolete schemas.

Here's the last version of the commodity/1 schema: https://github.com/jamesremuscat/EDDN/tree/8fa93fbb409a91eb5d7dee42f6cf86e940e4aa51/schemas
And of the commodity/2, outfitting/1 and shipyard/1 schemas: https://github.com/jamesremuscat/EDDN/tree/2d6e7d9f3827fb65a5a969ed5b1cb141c3078ff2/schemas

**Comment by jamesremuscat** [comment]
Just a note that `commodity/1`, `commodity/2` and `shipyard/1` are available at their canonical locations - that is, the location the schemas claim to be from, e.g. `http://schemas.elite-markets.net/eddn/_schema_/_version_`.

Newer versions and other schemas aren't there because, well, nobody's asked me to put them there...

**Comment by AnthorNet** [comment]
I recall having asked for that, but the email stayed without any response,
GitHub should suffice to see them anyway.
