### ISSUE TITLE
Population data on FSDJump Event

### ISSUE THREAD

**Issue by DarkMinded** [EDSM-NET/EDDN#67]
Considering 2.4 update to FSDJump Event on population are you including that on the Journal Schema ?

https://forums.frontier.co.uk/showthread.php/372993-2-4-Open-Beta-Patch-Notes

**Comment by AnthorNet** [comment]
It is up to the sender's to send that new field, but it should already done on the major ones without any necessary updates.

**Comment by Marginal** [comment]
Yes. e.g. https://ross.eddb.io/eddn/log/43076518

**Comment by DarkMinded** [comment]
thanks for the info, i will keep you informed of my progress ;)
