### ISSUE TITLE
MarketId is "number" in schema while it should be integer

### ISSUE THREAD

**Issue by DarkWanderer** [EDSM-NET/EDDN#87]
In several schemas, including for example Commodities, MarketId is specified to be "number" instead of "integer". This means that a producer which **strictly** conforms to schema may send market ID as "1234567.0". 

Some consumers (EDDB) consider ".0" suffix incorrect. I suggest to change the marketId field type to be integer, to avoid confusion

**Comment by nmanjos** [comment]
I use Long and it works just fine ...
