### ISSUE TITLE
Subscribe to topics?

### ISSUE THREAD

**Issue by dmon82** [EDSM-NET/EDDN#95]
Is there a way to subscribe to only one of the schemas (e. g. Commodity v3) as a consumer? I've googled around but it seems there's no way of getting a list of topics from the EDDN endpoint as a subscriber, nor did I find any information on how a consumer could set topic filters on EDDN, if there are topics at all to subcribe to.

Thank you  :)

**Comment by dmon82** [comment]
Duh, nevermind, I didn't realise I was searching only open issues. In [an earlier issue](https://github.com/EDSM-NET/EDDN/issues/34) it was mentioned to connect to a gateway to be able to use topic, because prepending text on the json object would break all then-current clients.

How do I connect to the gateway, if you don't mind? I'd rather subscribe to just a specific topic and not receive all other data at all, since I'd be discarding it.

**Comment by Tkael** [comment]
Here's the [official instructions](https://github.com/EDSM-NET/EDDN/wiki#trading-tool-developers-data-consumers). 
I don't think that customizing the output like you're describing is possible with the current architecture. The server posts the data to a single relay where it is not possible to customize outputs.

**Comment by AnthorNet** [comment]
Hi,

It's not doable in zeroMQ, what they do when subscribe n'to topic is only a filtering, you always receive every messages.

So just filter by schema :)

**Comment by dmon82** [comment]
I thought the Relay connected to the Gateway, and told the Gateway what messages to send to the Relay. And by connecting to the Gateway instead, you could choose what to receive like the Relay. And that the currently available Relay does, as you said, send everything with the topic stripped, which is just a JSON payload.

Or maybe what you were discussing was making several relays and actually start using topics to split the messages, which wasn't ever the behaviour... ah that must probably be the case. Let me grab a beer or five, I need to gain more insight through spiritual cleansing and meditation.

I already got the ZeroMQ connection running, quite a curious mashup of data formatting from all the different softwares. It's mighty awesome though, thank you for taking some time to reply and to get me thinking further, I got it all up and running as-is :)
